
<style>
    .help-block {
        color: red;
        font-size: 10px !important;
    }
    .error {
        border: 1px solid red;
    }
</style>
<form id="main-form" method="post" action="<?= base_url() ?>/employees/save">
    <div class="row">
        <div class="col-6">
            <!-- text input -->
            <div class="form-group">
                <label>Name <span class="text-danger">*</span></label>
                <input type="text" name="name" id="name" class="form-control nempty">
            </div>
            <div class="form-group">
                <label>Mobile Phone <span class="text-danger">*</span></label>
                <input type="text" name="mobile" id="mobile" class="form-control nempty">
            </div>
            <div class="form-group">
                <label>Address</label>
                <textarea name="address" id="address" class="form-control"></textarea>
            </div>        
        </div>    
    </div>
</form>