<?php
/**
 * Created by O2System Framework File Generator.
 * DateTime: 26/09/2019 08:09
 */

// ------------------------------------------------------------------------

namespace App\Controllers;

// ------------------------------------------------------------------------

use O2System\Framework\Http\Controller;

/**
 * Class Api
 *
 * @package \App\Controllers
 */
class Api extends Controller
{
    /**
     * Api::index
     */
    public function index()
    {
        // TODO: Change the autogenerated stub
    }
}